### ISSUE TITLE
Results of both versions of Livewire are showing up

### ISSUE THREAD

**Issue by fadarrizz** [AlexMartinFR/alfred-livewire-docs#1]
Results of both versions of Livewire are showing up. 

![image](https://user-images.githubusercontent.com/22003779/98015405-07d0fc00-1dfd-11eb-81bc-d431309ec88c.png)

It would be great if by default results from the latest release are shown, just like the Laravel workflow does.

**Comment by alexmartinfr** [comment]
Good find!
I'll update the workflow to fix that 👍

**Comment by alexmartinfr** [comment]
So I had some time to check the issue today.
I'll package a new version of the workflow soonish, but in the meantime here's the fix you can apply yourself if you want:

**Replace line 18** of the `livewire.php` file with the following:

```php
$search = $index->search($query, ['facetFilters' => [
    sprintf('version:%s', $branch ?: '2.x'),
]]);
```

**Comment by alexmartinfr** [comment]
Finally fixed it! Thanks again @Fadarrizz 🙂
