### ISSUE TITLE
Not working anymore on Monterey

### ISSUE THREAD

**Issue by christophrumpel** [AlexMartinFR/alfred-livewire-docs#2]
Hey. Since my upgrade to Mac OS Monterey, this workflow seems to be not working anymore.

I don't see any results anymore after typing what I want to look for in the docs.

It was the same with the Laravel Documentation workflow https://github.com/tillkruss/alfred-laravel-docs but I think they have handled it already. I updated to the latest version and it was working again.

<img width="686" alt="CleanShot 2021-11-09 at 09 07 00@2x" src="https://user-images.githubusercontent.com/1394539/140885868-ff5fd22a-53f4-4d79-98b6-997977945013.png">
<img width="666" alt="CleanShot 2021-11-09 at 09 06 52@2x" src="https://user-images.githubusercontent.com/1394539/140885876-7fbe567a-9ed8-4be9-aa37-0154a1a0970f.png">

**Comment by alexmartinfr** [comment]
Hi Cristoph!

Indeed, Apple finally dropped native PHP support with macOS Monterey.

I see that Till used Homebrew's PHP path instead: `/opt/homebrew/bin/php`.
This might be a problem for users of older versions of macOS / Intel Macs though.

Can you update the script filter like so and tell me if it works for you?

```bash
export PATH="/opt/homebrew/bin:/usr/local/bin:${PATH}"

php livewire.php "{query}"
```

![image](https://user-images.githubusercontent.com/19224681/140907028-b5ca10dc-78bb-479d-bd5a-5b21e95f8cb4.png)

**Comment by jonneroelofs** [comment]
Hi Alex,

I can confirm your suggestion fixes the problem for me.

Cheers

**Comment by christophrumpel** [comment]
it works indeed, thanks a lot!
