### ISSUE TITLE
Not working with PHP 8.2

### ISSUE THREAD

**Issue by mhoffmann777** [AlexMartinFR/alfred-livewire-docs#4]

**Comment by dmitry-ivanov** [comment]
@mhoffmann777 Sorry, why have you closed an issue? It looks like the workflow code still uses dynamic properties which are deprecated in PHP 8.2.

There's a workaround to disable error output, of course, but it will not work on further PHP versions anyway.

@AlexMartinFR If you'd have time, would be really nice to support PHP 8.2 fully (as Laravel Docs Workflow did).

Thank you!
